version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      - node
  node:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: npm install
